version: "3"

services:
    php:
        build: ./docker/php
        volumes:
            - ./www:/usr/share/nginx/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    nginx:
        image: "nginx:1.19.1-alpine"
        volumes:
            - ./www:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9999:80"
        depends_on:
            - "php"
